
module.exports = {

darkMode: "class",
        theme: {
          extend: {
            colors: {
              "outline": "#727780",
              "on-surface": "#111d23",
              "surface-container-highest": "#d7e4ec",
              "error-container": "#ffdad6",
              "on-primary-fixed-variant": "#00497b",
              "on-secondary-fixed": "#271900",
              "error": "#ba1a1a",
              "tertiary-fixed-dim": "#b4cad6",
              "inverse-on-surface": "#e6f3fb",
              "on-primary-container": "#87baf3",
              "on-tertiary": "#ffffff",
              "inverse-surface": "#263238",
              "secondary-container": "#feb700",
              "tertiary-fixed": "#cfe6f2",
              "tertiary-container": "#354a54",
              "on-tertiary-fixed": "#071e27",
              "surface-variant": "#d7e4ec",
              "on-error-container": "#93000a",
              "on-tertiary-fixed-variant": "#354a53",
              "surface": "#f4faff",
              "on-background": "#111d23",
              "primary-fixed": "#d0e4ff",
              "outline-variant": "#c1c7d0",
              "secondary": "#7c5800",
              "on-primary-fixed": "#001d35",
              "surface-container": "#e3f0f8",
              "on-error": "#ffffff",
              "primary-fixed-dim": "#9ccaff",
              "surface-dim": "#cfdce4",
              "tertiary": "#1e333d",
              "surface-bright": "#f4faff",
              "on-tertiary-container": "#a3b9c4",
              "inverse-primary": "#9ccaff",
              "surface-container-low": "#e9f6fd",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed-dim": "#ffba20",
              "on-secondary-container": "#6b4b00",
              "surface-container-high": "#ddeaf2",
              "on-secondary-fixed-variant": "#5e4200",
              "surface-tint": "#296195",
              "secondary-fixed": "#ffdea8",
              "primary": "#004A7C",
              "on-primary": "#ffffff",
              "primary-container": "#00497b",
              "background": "#f4faff",
              "on-surface-variant": "#42474f",
              "on-secondary": "#ffffff"
            },
            fontFamily: {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
    }